# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ph1p6JCnfcWOppl-SDLYPiTKEtN37vRG
"""

!pip install -q kaggle

import os, json, shutil

# 1) перемещаем kaggle.json, который ты загрузишь через Files в /content
os.makedirs(os.path.join(os.path.expanduser("~"), ".kaggle"), exist_ok=True)
if os.path.exists("kaggle.json"):
    shutil.move("kaggle.json", os.path.join(os.path.expanduser("~"), ".kaggle", "kaggle.json"))
    print("kaggle.json перемещён в ~/.kaggle")
else:
    print("⚠️ Загрузите kaggle.json в /content через панель Files!")

os.chmod(os.path.join(os.path.expanduser("~"), ".kaggle", "kaggle.json"), 0o600)

# 2) создаём папку data и скачиваем датасет Fantacher "Metal Surface Defects Dataset" [web:25][web:28]
os.makedirs("data", exist_ok=True)

!kaggle datasets download -d fantacher/neu-metal-surface-defects-data -p data

# 3) распаковываем zip
import zipfile
zip_path = "data/neu-metal-surface-defects-data.zip"
with zipfile.ZipFile(zip_path, "r") as zf:
    zf.extractall("data")
print("Распаковано в ./data")

import tensorflow as tf

# ищем папку, где лежат 6 подпапок классов (Crazing, Inclusion, Patches, Pitted, Rolled, Scratches) [web:25][web:33]
def find_class_root(base_dir):
    for root, dirs, files in os.walk(base_dir):
        lower_dirs = [d.lower() for d in dirs]
        needed = ["crazing", "inclusion", "patches", "pitted", "rolled", "scratches"]
        if all(any(nd == need for nd in lower_dirs) for need in needed):
            return root
    return None

BASE_DIR = "./data"
train_root = find_class_root(BASE_DIR)
print("train_root =", train_root)
print("Подпапки:", os.listdir(train_root))

CONFIG = {
    "img_height": 128,
    "img_width": 128,
    "batch_size": 32,
    "seed": 42,
    "val_split": 0.2,
    "test_split": 0.1,
    "epochs": 15,
    "base_filters": 32,
    "conv_blocks": 3,
    "dropout": 0.4,
    "learning_rate": 1e-3,
}

IMG_SIZE   = (CONFIG["img_height"], CONFIG["img_width"])
BATCH_SIZE = CONFIG["batch_size"]
SEED       = CONFIG["seed"]

full_ds = tf.keras.utils.image_dataset_from_directory(
    train_root,
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    seed=SEED,
    shuffle=True,
)

class_names = full_ds.class_names
num_classes = len(class_names)
print("class_names:", class_names, "num_classes =", num_classes)

total_batches = tf.data.experimental.cardinality(full_ds).numpy()
val_batches   = int(total_batches * CONFIG["val_split"])
test_batches  = int(total_batches * CONFIG["test_split"])
train_batches = total_batches - val_batches - test_batches

print(f"Всего батчей: {total_batches}")
print(f"Train: {train_batches}, Val: {val_batches}, Test: {test_batches}")

train_ds = full_ds.take(train_batches)
val_ds   = full_ds.skip(train_batches).take(val_batches)
test_ds  = full_ds.skip(train_batches + val_batches)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(AUTOTUNE)
val_ds   = val_ds.cache().prefetch(AUTOTUNE)
test_ds  = test_ds.cache().prefetch(AUTOTUNE)

train_root = "./data/NEU Metal Surface Defects Data/train"
print("train_root =", train_root)
print("Подпапки:", os.listdir(train_root))

IMG_SIZE   = (CONFIG["img_height"], CONFIG["img_width"])
BATCH_SIZE = CONFIG["batch_size"]
SEED       = CONFIG["seed"]

full_ds = tf.keras.utils.image_dataset_from_directory(
    train_root,
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    seed=SEED,
    shuffle=True,
)

class_names = full_ds.class_names
num_classes = len(class_names)

total_batches = tf.data.experimental.cardinality(full_ds).numpy()
val_batches   = int(total_batches * CONFIG["val_split"])
test_batches  = int(total_batches * CONFIG["test_split"])
train_batches = total_batches - val_batches - test_batches

print(f"Всего батчей: {total_batches}")
print(f"Train: {train_batches}, Val: {val_batches}, Test: {test_batches}")

import os, tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

# 1. ДАННЫЕ
train_root = "./data/NEU Metal Surface Defects Data/train"
print("train_root =", train_root)
print("Подпапки:", os.listdir(train_root))

IMG_SIZE   = (CONFIG["img_height"], CONFIG["img_width"])
BATCH_SIZE = CONFIG["batch_size"]
SEED       = CONFIG["seed"]

full_ds = tf.keras.utils.image_dataset_from_directory(
    train_root,
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    seed=SEED,
    shuffle=True,
)

class_names = full_ds.class_names
num_classes = len(class_names)
print("class_names:", class_names, "num_classes =", num_classes)

total_batches = tf.data.experimental.cardinality(full_ds).numpy()
val_batches   = int(total_batches * CONFIG["val_split"])
test_batches  = int(total_batches * CONFIG["test_split"])
train_batches = total_batches - val_batches - test_batches

print(f"Всего батчей: {total_batches}")
print(f"Train: {train_batches}, Val: {val_batches}, Test: {test_batches}")

train_ds = full_ds.take(train_batches)
val_ds   = full_ds.skip(train_batches).take(val_batches)
test_ds  = full_ds.skip(train_batches + val_batches)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(AUTOTUNE)
val_ds   = val_ds.cache().prefetch(AUTOTUNE)
test_ds  = test_ds.cache().prefetch(AUTOTUNE)

print("train_ds batches:", tf.data.experimental.cardinality(train_ds).numpy())
print("val_ds batches:",   tf.data.experimental.cardinality(val_ds).numpy())
print("test_ds batches:",  tf.data.experimental.cardinality(test_ds).numpy())

# 2. МОДЕЛЬ
data_augmentation = keras.Sequential(
    [
        layers.RandomFlip("horizontal"),
        layers.RandomRotation(0.1),
        layers.RandomZoom(0.1),
    ]
)

def build_cnn_model(
    img_size=IMG_SIZE,
    num_classes=num_classes,
    base_filters=32,
    conv_blocks=3,
    dropout=0.4,
):
    inputs = keras.Input(shape=img_size + (3,))
    x = data_augmentation(inputs)
    x = layers.Rescaling(1.0 / 255)(x)

    filters = base_filters
    for _ in range(conv_blocks):
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.MaxPooling2D()(x)
        filters *= 2

    x = layers.Flatten()(x)
    x = layers.Dense(256, activation="relu")(x)
    x = layers.Dropout(dropout)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)

    model = keras.Model(inputs, outputs, name="metal_defect_cnn")
    return model

model = build_cnn_model(
    img_size=IMG_SIZE,
    num_classes=num_classes,
    base_filters=CONFIG["base_filters"],
    conv_blocks=CONFIG["conv_blocks"],
    dropout=CONFIG["dropout"],
)

model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=CONFIG["learning_rate"]),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

model.summary()

callbacks = [
    keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True,
    )
]

# 3. ОБУЧЕНИЕ
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=CONFIG["epochs"],
    callbacks=callbacks,
)

test_loss, test_acc = model.evaluate(test_ds)
print(f"Test accuracy: {test_acc:.4f}, loss: {test_loss:.4f}")

# 4. ГРАФИКИ
acc      = history.history["accuracy"]
val_acc  = history.history["val_accuracy"]
loss     = history.history["loss"]
val_loss = history.history["val_loss"]
epochs_range = range(1, len(acc) + 1)

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label="Обучающая точность")
plt.plot(epochs_range, val_acc, label="Валидационная точность")
plt.xlabel("Эпоха")
plt.ylabel("Точность")
plt.title("Точность обучения и валидации")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label="Обучающая функция потерь")
plt.plot(epochs_range, val_loss, label="Валидационная функция потерь")
plt.xlabel("Эпоха")
plt.ylabel("Функция потерь")
plt.title("Функция потерь обучения и валидации")
plt.legend()

plt.tight_layout()
plt.show()

def build_cnn_model_v2(img_size=IMG_SIZE, num_classes=num_classes):
    inputs = keras.Input(shape=img_size + (3,))
    x = data_augmentation(inputs)
    x = layers.Rescaling(1.0 / 255)(x)

    # пример: только 2 блока вместо 3
    for filters in [32, 64]:
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.MaxPooling2D()(x)

    x = layers.Flatten()(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.4)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)

    return keras.Model(inputs, outputs, name="metal_defect_cnn_v2")

model2 = build_cnn_model_v2()
model2.compile(
    optimizer=keras.optimizers.Adam(learning_rate=CONFIG["learning_rate"]),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

history2 = model2.fit(
    train_ds,
    validation_data=val_ds,
    epochs=CONFIG["epochs"],
)

test_loss2, test_acc2 = model2.evaluate(test_ds)
print("Model2 test acc:", test_acc2)

!pip install -q kaggle

import os, shutil, zipfile

# 1) kaggle.json загрузи через панель Files в /content, потом:
os.makedirs(os.path.join(os.path.expanduser("~"), ".kaggle"), exist_ok=True)
if os.path.exists("kaggle.json"):
    shutil.move("kaggle.json", os.path.join(os.path.expanduser("~"), ".kaggle", "kaggle.json"))
    print("kaggle.json перемещён")
os.chmod(os.path.join(os.path.expanduser("~"), ".kaggle", "kaggle.json"), 0o600)

# 2) скачиваем датасет
os.makedirs("data", exist_ok=True)
!kaggle datasets download -d fantacher/neu-metal-surface-defects-data -p data

import zipfile, os

zip_path = "data/neu-metal-surface-defects-data.zip"
extract_dir = "data"

with zipfile.ZipFile(zip_path, "r") as zf:
    zf.extractall(extract_dir)

print("Содержимое ./data:", os.listdir("data"))

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import os

CONFIG = {
    "img_height": 128,
    "img_width": 128,
    "batch_size": 32,
    "seed": 42,
    "val_split": 0.2,
    "test_split": 0.1,
    "epochs": 10,
    "learning_rate": 1e-3,
}

train_root = "./data/NEU Metal Surface Defects Data/train"
print("train_root =", train_root)
print("Подпапки train:", os.listdir(train_root))

IMG_SIZE   = (CONFIG["img_height"], CONFIG["img_width"])
BATCH_SIZE = CONFIG["batch_size"]
SEED       = CONFIG["seed"]

full_ds = tf.keras.utils.image_dataset_from_directory(
    train_root,
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    seed=SEED,
    shuffle=True,
)

class_names = full_ds.class_names
num_classes = len(class_names)
print("class_names:", class_names, "num_classes =", num_classes)

total_batches = tf.data.experimental.cardinality(full_ds).numpy()
val_batches   = int(total_batches * CONFIG["val_split"])
test_batches  = int(total_batches * CONFIG["test_split"])
train_batches = total_batches - val_batches - test_batches

print(f"Всего батчей: {total_batches}")
print(f"Train: {train_batches}, Val: {val_batches}, Test: {test_batches}")

train_ds = full_ds.take(train_batches)
val_ds   = full_ds.skip(train_batches).take(val_batches)
test_ds  = full_ds.skip(train_batches + val_batches)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(AUTOTUNE)
val_ds   = val_ds.cache().prefetch(AUTOTUNE)
test_ds  = test_ds.cache().prefetch(AUTOTUNE)

data_augmentation = keras.Sequential(
    [
        layers.RandomFlip("horizontal"),
        layers.RandomRotation(0.1),
        layers.RandomZoom(0.1),
    ]
)

def build_cnn_model_v2(img_size=IMG_SIZE, num_classes=num_classes):
    inputs = keras.Input(shape=img_size + (3,))
    x = data_augmentation(inputs)
    x = layers.Rescaling(1.0 / 255)(x)

    for filters in [32, 64]:
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.MaxPooling2D()(x)

    x = layers.Flatten()(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.4)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)

    return keras.Model(inputs, outputs, name="metal_defect_cnn_v2")

model2 = build_cnn_model_v2()
model2.compile(
    optimizer=keras.optimizers.Adam(learning_rate=CONFIG["learning_rate"]),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

history2 = model2.fit(
    train_ds,
    validation_data=val_ds,
    epochs=CONFIG["epochs"],
)

test_loss2, test_acc2 = model2.evaluate(test_ds)
print(f"Model2 test accuracy: {test_acc2:.4f}, loss: {test_loss2:.4f}")

# Графики для Алгоритма 2
acc      = history2.history["accuracy"]
val_acc  = history2.history["val_accuracy"]
loss     = history2.history["loss"]
val_loss = history2.history["val_loss"]
epochs   = range(1, len(acc) + 1)

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(epochs, acc, label="Обучающая точность")
plt.plot(epochs, val_acc, label="Валидационная точность")
plt.xlabel("Эпоха")
plt.ylabel("Точность")
plt.title("Точность обучения и валидации (Алгоритм 2)")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(epochs, loss, label="Обучающая функция потерь")
plt.plot(epochs, val_loss, label="Валидационная функция потерь")
plt.xlabel("Эпоха")
plt.ylabel("Функция потерь")
plt.title("Функция потерь обучения и валидации (Алгоритм 2)")
plt.legend()

plt.tight_layout()
plt.show()

from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt

# Модель можно взять такую же, как в Алгоритме 2
def build_cnn_model_v2(img_size=IMG_SIZE, num_classes=num_classes):
    inputs = keras.Input(shape=img_size + (3,))
    x = data_augmentation(inputs)
    x = layers.Rescaling(1.0 / 255)(x)

    for filters in [32, 64]:
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.Conv2D(filters, 3, padding="same", activation="relu")(x)
        x = layers.MaxPooling2D()(x)

    x = layers.Flatten()(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.Dropout(0.4)(x)
    outputs = layers.Dense(num_classes, activation="softmax")(x)

    return keras.Model(inputs, outputs, name="metal_defect_cnn_v2_sgd")

model3 = build_cnn_model_v2()

# ВАЖНО: другой оптимизатор — SGD с momentum
opt = keras.optimizers.SGD(learning_rate=0.01, momentum=0.9)  # алгоритм 3

model3.compile(
    optimizer=opt,
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

model3.summary()

history3 = model3.fit(
    train_ds,
    validation_data=val_ds,
    epochs=CONFIG["epochs"],
)

test_loss3, test_acc3 = model3.evaluate(test_ds)
print(f"Model3 (SGD) test accuracy: {test_acc3:.4f}, loss: {test_loss3:.4f}")

# Графики для Алгоритма 3
acc      = history3.history["accuracy"]
val_acc  = history3.history["val_accuracy"]
loss     = history3.history["loss"]
val_loss = history3.history["val_loss"]
epochs   = range(1, len(acc) + 1)

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(epochs, acc, label="Обучающая точность")
plt.plot(epochs, val_acc, label="Валидационная точность")
plt.xlabel("Эпоха")
plt.ylabel("Точность")
plt.title("Точность обучения и валидации (Алгоритм 3, SGD)")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(epochs, loss, label="Обучающая функция потерь")
plt.plot(epochs, val_loss, label="Валидационная функция потерь")
plt.xlabel("Эпоха")
plt.ylabel("Функция потерь")
plt.title("Функция потерь обучения и валидации (Алгоритм 3, SGD)")
plt.legend()

plt.tight_layout()
plt.show()

!pip install -q kaggle

import os, shutil, zipfile

# 1) Загрузите kaggle.json через панель Files в /content
os.makedirs(os.path.join(os.path.expanduser("~"), ".kaggle"), exist_ok=True)
if os.path.exists("kaggle.json"):
    shutil.move("kaggle.json", os.path.join(os.path.expanduser("~"), ".kaggle", "kaggle.json"))
    print("kaggle.json перемещён в ~/.kaggle")
else:
    print("⚠️ Загрузите kaggle.json в корень /content!")

os.chmod(os.path.join(os.path.expanduser("~"), ".kaggle", "kaggle.json"), 0o600)

# 2) Скачиваем датасет Fantacher NEU Metal Surface Defects [web:25][web:163]
os.makedirs("data", exist_ok=True)
!kaggle datasets download -d fantacher/neu-metal-surface-defects-data -p data

import zipfile, os

zip_path = "data/neu-metal-surface-defects-data.zip"
extract_dir = "data"

with zipfile.ZipFile(zip_path, "r") as zf:
    zf.extractall(extract_dir)

print("Содержимое ./data:", os.listdir("data"))

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import os

CONFIG = {
    "img_height": 128,
    "img_width": 128,
    "batch_size": 32,
    "seed": 42,
    "val_split": 0.2,
    "test_split": 0.1,
    "epochs": 10,
    "learning_rate": 1e-3,
}

train_root = "./data/NEU Metal Surface Defects Data/train"
print("train_root =", train_root)
print("Подпапки train:", os.listdir(train_root))

IMG_SIZE   = (CONFIG["img_height"], CONFIG["img_width"])
BATCH_SIZE = CONFIG["batch_size"]
SEED       = CONFIG["seed"]

full_ds = tf.keras.utils.image_dataset_from_directory(
    train_root,
    labels="inferred",
    label_mode="int",
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    seed=SEED,
    shuffle=True,
)

class_names = full_ds.class_names
num_classes = len(class_names)
print("class_names:", class_names, "num_classes =", num_classes)

total_batches = tf.data.experimental.cardinality(full_ds).numpy()
val_batches   = int(total_batches * CONFIG["val_split"])
test_batches  = int(total_batches * CONFIG["test_split"])
train_batches = total_batches - val_batches - test_batches

print(f"Всего батчей: {total_batches}")
print(f"Train: {train_batches}, Val: {val_batches}, Test: {test_batches}")

train_ds = full_ds.take(train_batches)
val_ds   = full_ds.skip(train_batches).take(val_batches)
test_ds  = full_ds.skip(train_batches + val_batches)

AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(AUTOTUNE)
val_ds   = val_ds.cache().prefetch(AUTOTUNE)
test_ds  = test_ds.cache().prefetch(AUTOTUNE)

data_augmentation = keras.Sequential(
    [
        layers.RandomFlip("horizontal"),
        layers.RandomRotation(0.1),
        layers.RandomZoom(0.1),
    ]
)

import matplotlib.pyplot as plt
from tensorflow.keras import applications

# 1) Базовая предобученная модель MobileNetV2 [web:111]
base_model = applications.MobileNetV2(
    input_shape=IMG_SIZE + (3,),
    include_top=False,
    weights="imagenet"
)
base_model.trainable = False  # сначала заморожены все слои

# 2) Строим свою «голову» для 6 классов дефектов
inputs = keras.Input(shape=IMG_SIZE + (3,))
x = data_augmentation(inputs)
x = applications.mobilenet_v2.preprocess_input(x)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(num_classes, activation="softmax")(x)

model4 = keras.Model(inputs, outputs, name="mobilenetv2_defects")

model4.compile(
    optimizer=keras.optimizers.Adam(learning_rate=CONFIG["learning_rate"]),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"],
)

model4.summary()

# 3) Обучение (Алгоритм 4)
history4 = model4.fit(
    train_ds,
    validation_data=val_ds,
    epochs=CONFIG["epochs"],
)

test_loss4, test_acc4 = model4.evaluate(test_ds)
print(f"MobileNetV2 test accuracy: {test_acc4:.4f}, loss: {test_loss4:.4f}")

acc      = history4.history["accuracy"]
val_acc  = history4.history["val_accuracy"]
loss     = history4.history["loss"]
val_loss = history4.history["val_loss"]
epochs   = range(1, len(acc) + 1)

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(epochs, acc, label="Обучающая точность")
plt.plot(epochs, val_acc, label="Валидационная точность")
plt.xlabel("Эпоха")
plt.ylabel("Точность")
plt.title("Точность обучения и валидации (Алгоритм 4, MobileNetV2)")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(epochs, loss, label="Обучающая функция потерь")
plt.plot(epochs, val_loss, label="Валидационная функция потерь")
plt.xlabel("Эпоха")
plt.ylabel("Функция потерь")
plt.title("Потери обучения и валидации (Алгоритм 4, MobileNetV2)")
plt.legend()

plt.tight_layout()
plt.show()

import gc
import tensorflow as tf
import numpy as np

# 1) Очистка памяти GPU/TPU
tf.keras.backend.clear_session()
gc.collect()

# 2) Удаление предыдущих моделей и датасетов
try:
    del model4, model5, base_model
    del train_ds, val_ds, test_ds, full_ds
    del history4, history_fine, history_combined
except:
    pass

# 3) Современная очистка для TF 2.x (set_learning_phase устарел)
tf.config.optimizer.set_jit(False)  # XLA off
gc.collect()

# 4) Проверка GPU памяти
try:
    gpu_info = tf.config.experimental.get_memory_info('GPU:0')
    print(f"✅ Память очищена. GPU: {gpu_info['current'] / 1e9:.1f} GB")
except:
    print("✅ Память очищена (CPU mode)")

print("🚀 Готов к Алгоритму 5!")

import tensorflow as tf
from tensorflow.keras import layers, applications
import matplotlib.pyplot as plt

print("=== АЛГОРИТМ 5: Fine-tuning MobileNetV2 (полная перезагрузка) ===")

# 1) Пересоздаём датасеты и MobileNetV2 с нуля
IMG_SIZE = (128, 128)
BATCH_SIZE = 32
train_root = "./data/NEU Metal Surface Defects Data/train"

full_ds = tf.keras.utils.image_dataset_from_directory(
    train_root, image_size=IMG_SIZE, batch_size=BATCH_SIZE, seed=42, shuffle=True
)
class_names = full_ds.class_names
num_classes = len(class_names)

# Разделение на train/val/test
total = tf.data.experimental.cardinality(full_ds).numpy()
train_ds = full_ds.take(30).cache().shuffle(1000).prefetch(tf.data.AUTOTUNE)
val_ds = full_ds.skip(30).take(4).cache().prefetch(tf.data.AUTOTUNE)
test_ds = full_ds.skip(34)

# 2) Создаём MobileNetV2 заново (как в Алгоритме 4)
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
])

base_model = applications.MobileNetV2(
    input_shape=IMG_SIZE + (3,), include_top=False, weights="imagenet"
)
base_model.trainable = False

inputs = tf.keras.Input(shape=IMG_SIZE + (3,))
x = data_augmentation(inputs)
x = applications.mobilenet_v2.preprocess_input(x)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(num_classes, activation="softmax")(x)

model5 = tf.keras.Model(inputs, outputs)
model5.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Быстрое обучение базовой модели (10 эпох)
print("🔄 Быстрое обучение базовой MobileNetV2...")
history_base = model5.fit(train_ds, validation_data=val_ds, epochs=10, verbose=1)

test_loss_base, test_acc_base = model5.evaluate(test_ds, verbose=0)
print(f"Базовая MobileNetV2: test acc = {test_acc_base:.4f}")

# 3) Fine-tuning: размораживаем последние 20 слоёв
base_model.trainable = True
fine_tune_at = len(base_model.layers) - 20
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False

model5.compile(
    optimizer=tf.keras.optimizers.Adam(1e-4),  # Маленький LR
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print(f"🔄 Fine-tuning последних {len(base_model.layers) - fine_tune_at} слоёв...")
history_fine = model5.fit(
    train_ds, validation_data=val_ds, epochs=5, verbose=1
)

test_loss5, test_acc5 = model5.evaluate(test_ds, verbose=0)
print(f"\n✅ Fine-tune результат: {test_acc5:.4f}")
print(f"Улучшение: {test_acc5 - test_acc_base:+.4f}")

import matplotlib.pyplot as plt

# График ТОЛЬКО для Алгоритма 5 (как у алгоритмов 1-4)
plt.figure(figsize=(12, 4))

# Точность
plt.subplot(1, 2, 1)
plt.plot(history_fine.history["accuracy"], label="Обучающая точность")
plt.plot(history_fine.history["val_accuracy"], label="Валидационная точность")
plt.xlabel("Эпоха")
plt.ylabel("Точность")
plt.title("Точность обучения и валидации (Алгоритм 5, MobileNetV2 Fine-tune)")
plt.legend()
plt.grid(True)

# Потери
plt.subplot(1, 2, 2)
plt.plot(history_fine.history["loss"], label="Обучающая функция потерь")
plt.plot(history_fine.history["val_loss"], label="Валидационная функция потерь")
plt.xlabel("Эпоха")
plt.ylabel("Функция потерь")
plt.title("Потери обучения и валидации (Алгоритм 5, MobileNetV2 Fine-tune)")
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

print(f"✅ Алгоритм 5: test accuracy = {test_acc5:.4f}")

